import Header from "@/components/feautures/header";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Toaster } from "@/components/ui/sonner";
import {
  CircleCheckBigIcon,
  CircleOff,
  InfoIcon,
  LoaderCircleIcon,
  TriangleAlertIcon,
  XCircleIcon,
} from "lucide-react";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-poppins antialiased`}
      >
        <ThemeProvider storageKey="web-theme" attribute="class">
          <ScrollArea className="size-full">
            <Header/>
          {children}
          </ScrollArea>
          <Toaster
            icons={{
              close: <XCircleIcon />,
              success: <CircleCheckBigIcon />,
              error: <CircleOff />,
              info: <InfoIcon />,
              loading: <LoaderCircleIcon className="animate-spin" />,
              warning: <TriangleAlertIcon />,
            }}
            visibleToasts={3}
            swipeDirections={["top", "left", "right", "bottom"]}
            closeButton
            duration={3000}
            offset={{
              top: 20,
              bottom: 20,
              left: 20,
              right: 20,
            }}
            richColors
          />
        </ThemeProvider>
      </body>
    </html>
  );
}
