import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/lib/hooks/theme";
import {
  CircleCheckBigIcon,
  CircleOff,
  InfoIcon,
  LoaderCircleIcon,
  TriangleAlertIcon,
  XCircleIcon,
} from "lucide-react";
import type { Metadata } from "next";
import "./globals.css";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const themeCookie = "web-theme";
  const cookieStore = await cookies();
  const currentTheme = cookieStore.get(themeCookie);
  return (
    <html lang="en" className={currentTheme?.value === "dark" ? "dark" : ""}>
      <body className="font-poppins antialiased">
        <ThemeProvider cookieKey={themeCookie}>
          {children}

          <Toaster
            icons={{
              close: <XCircleIcon />,
              success: <CircleCheckBigIcon />,
              error: <CircleOff />,
              info: <InfoIcon />,
              loading: <LoaderCircleIcon className="animate-spin" />,
              warning: <TriangleAlertIcon />,
            }}
            visibleToasts={3}
            swipeDirections={["top", "left", "right", "bottom"]}
            closeButton
            duration={3000}
            offset={{
              top: 20,
              bottom: 20,
              left: 20,
              right: 20,
            }}
            richColors
          />
        </ThemeProvider>
      </body>
    </html>
  );
}
